"""Versioned normalization registries for protocol-specific mappings."""

from __future__ import annotations

NORMALIZATION_VERSION = "bacnet-v1"

BACNET_DATA_TYPE_PREFIXES: dict[str, str] = {
    "analog": "float",
    "binary": "bool",
    "multistate": "enum",
    "characterstring": "string",
}

BACNET_DATA_TYPE_BY_OBJECT_TYPE: dict[str, str] = {
    "largeanalogvalue": "float",
    "pulseconverter": "float",
    "accumulator": "float",
    "integervalue": "int",
    "positiveintegervalue": "int",
    "datetimevalue": "datetime",
    "datevalue": "date",
    "timevalue": "time",
}

BACNET_ACCESS_BY_OBJECT_TYPE: dict[str, str] = {
    "schedule": "read-write",
    "calendar": "read-write",
    "program": "read-write",
    "loop": "read-write",
    "command": "read-write",
    "trendlog": "read",
    "trendlogmultiple": "read",
    "eventlog": "read",
}

BACNET_CANONICAL_UNITS_BY_NAME: dict[str, str] = {
    "volts": "V",
    "volt": "V",
    "amperes": "A",
    "ampere": "A",
    "amps": "A",
    "amp": "A",
    "kilovolt-amperes": "kVA",
    "kva": "kVA",
    "kilovars": "kvar",
    "kvar": "kvar",
    "kilowatts": "kW",
    "kilowatt": "kW",
    "kilowatt-hours": "kWh",
    "kilowatt-hour": "kWh",
    "kwh": "kWh",
    "kw": "kW",
    "watts": "W",
    "watt": "W",
    "hertz": "Hz",
    "hz": "Hz",
    "percent": "%",
    "percentage": "%",
    "degrees-celsius": "C",
    "celsius": "C",
    "degrees-fahrenheit": "F",
    "fahrenheit": "F",
    "psi": "psi",
    "pascal": "Pa",
    "meters": "m",
    "meter": "m",
    "feet": "ft",
    "foot": "ft",
    "inches": "in",
    "inch": "in",
    "liters": "L",
    "liter": "L",
    "milliliters": "mL",
    "milliliter": "mL",
    "gallons": "gal",
    "gallon": "gal",
    "cubic-meters-per-hour": "m3/h",
    "cubic-meters-per-second": "m3/s",
    "liters-per-second": "L/s",
    "liters-per-minute": "L/min",
    "liters-per-hour": "L/h",
    "ppm": "ppm",
    "ppb": "ppb",
    "power-factor": "",
    "powerfactor": "",
    "dimensionless": "",
    "no-units": "",
    "seconds": "s",
    "minutes": "min",
    "hours": "h",
}

BACNET_CANONICAL_UNITS_BY_ID: dict[str, str] = {
    "3": "A",
    "4": "mA",
    "5": "V",
    "6": "mV",
    "9": "Pa",
    "10": "kPa",
    "18": "Wh",
    "19": "kWh",
    "20": "MWh",
    "27": "Hz",
    "36": "foot-candles",
    "37": "lux",
    "42": "L/s",
    "43": "cfm",
    "47": "W",
    "48": "kW",
    "49": "MW",
    "53": "kVA",
    "54": "kvar",
    "62": "C",
    "63": "K",
    "64": "F",
    "75": "km",
    "76": "m",
    "77": "cm",
    "78": "mm",
    "79": "ft",
    "80": "in",
    "90": "deg",
    "95": "",
    "98": "%",
    "133": "psi",
    "159": "s",
    "160": "min",
    "161": "h",
    "162": "days",
}

BACNET_QUANTITY_BY_UNIT: dict[str, str] = {
    "c": "temperature",
    "f": "temperature",
    "k": "temperature",
    "deg": "angle",
    "rad": "angle",
    "%": "ratio",
    "ratio": "ratio",
    "pa": "pressure",
    "kpa": "pressure",
    "bar": "pressure",
    "mbar": "pressure",
    "inh2o": "pressure",
    "psi": "pressure",
    "v": "voltage",
    "mv": "voltage",
    "kv": "voltage",
    "a": "current",
    "ma": "current",
    "ka": "current",
    "w": "power",
    "kw": "power",
    "mw": "power",
    "va": "power",
    "kva": "power",
    "var": "power",
    "kvar": "power",
    "wh": "energy",
    "kwh": "energy",
    "mwh": "energy",
    "j": "energy",
    "kj": "energy",
    "mj": "energy",
    "hz": "frequency",
    "s": "time",
    "min": "time",
    "h": "time",
    "days": "time",
    "m": "length",
    "cm": "length",
    "mm": "length",
    "km": "length",
    "ft": "length",
    "in": "length",
    "l": "volume",
    "ml": "volume",
    "gal": "volume",
    "l/s": "flow",
    "l/min": "flow",
    "l/h": "flow",
    "m3/s": "flow",
    "m3/h": "flow",
    "cfm": "flow",
    "gpm": "flow",
    "kg": "mass",
    "g": "mass",
    "kg/s": "mass_flow",
    "lux": "illuminance",
    "foot-candles": "illuminance",
    "ppm": "concentration",
    "ppb": "concentration",
}

BACNET_MEDIUM_BY_PREFIX: dict[str, str] = {
    "analog": "analog",
    "binary": "digital",
    "multistate": "multistate",
    "characterstring": "data",
}

BACNET_MEDIUM_BY_OBJECT_TYPE: dict[str, str] = {
    "largeanalogvalue": "analog",
    "pulseconverter": "analog",
    "accumulator": "analog",
    "integervalue": "data",
    "positiveintegervalue": "data",
    "datetimevalue": "data",
    "datevalue": "data",
    "timevalue": "data",
    "trendlog": "log",
    "trendlogmultiple": "log",
    "eventlog": "log",
    "notificationclass": "event",
    "eventenrollment": "event",
    "schedule": "control",
    "calendar": "control",
    "program": "control",
}
